#pragma kernel CSMain
 
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl"

RW_TEXTURE2D_X(float4, CameraBuffer);
TEXTURE2D(StylizedTexture);

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 color = float4(StylizedTexture[id.xy].rgb, 0.2);
    CameraBuffer[uint3(id.xy, 0)].rgba = color;
}
